name: Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: kskshaf/build-aur-vsplugins-action@main
      with:
        repo-name: vs-plugins-build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: pack
        path: build.tar.gz
